<a href="https://colab.research.google.com/github/chav120/Introduction-to-Dataframes/blob/main/HW2_Chavez_Joseph.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
import pandas as pd

print("1-1")
frame = pd.DataFrame(data)
print(frame)

print("\n")
print("1-2")
jobFinder = frame[(frame["job"] == "psychologist") & (frame["num_cars"] > frame["family_size"])]
jobFinder2 = frame[(frame["job"] == "teacher") & (frame["num_cars"] > frame["family_size"])]
print("Psychologists:")
print(jobFinder, "\n")
print("Teachers:")
print(jobFinder2)

print("\n")
print("1-3")
print(frame[(frame["family_size"] <= 2) & (frame["num_cars"] >= 1)])

print("\n")
print("1-4")
uniqueJobs = []
for i in frame["job"]:
  if i not in uniqueJobs:
    uniqueJobs.append(i)
print("The number of unique jobs is", len(uniqueJobs))


1-1
     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1


1-2
Psychologists:
   name           job  family_size  num_cars
5  Lisa  psychologist            3         4 

Teachers:
Empty DataFrame
Columns: [name, job, family_size, num_cars]
Index: []


1-3
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1


1-4
The number of unique jobs is 4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
import numpy as np
import pandas as pd
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

fruitList = np.array(fruit)
weightList = np.array(weights)

fruits = {"fruits": fruitList,
          "weights": weightList}

fruitsFrame = pd.DataFrame(fruits)

print(fruitsFrame)

appleWeight = fruitsFrame[fruitsFrame["fruits"] == "apple"]
print("Apples", str(np.mean(appleWeight)))

bananaWeight = fruitsFrame[fruitsFrame["fruits"] == "banana"]
print("Bananas", str(np.mean(bananaWeight)))

carrotWeight = fruitsFrame[fruitsFrame["fruits"] == "carrot"]
print("Carrots", str(np.mean(carrotWeight)))

print("Total mean is", str(np.mean(weights)))












   fruits  weights
0  carrot      1.0
1   apple      2.0
2  banana      3.0
3  banana      4.0
4  banana      5.0
5  banana      6.0
6   apple      7.0
7   apple      8.0
8   apple      9.0
9   apple     10.0
Apples weights    7.2
dtype: float64
Bananas weights    4.5
dtype: float64
Carrots weights    1.0
dtype: float64
Total mean is 5.5


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

print("3-1")
sortedList = np.sort(course_name)
print("Sorted List:", sortedList)

for i in course_name:
  index = np.where(sortedList == i)
  print(i, "Sorted Index:", index[0])

print("\n")
print("3-2")
for i in course_name:
  newList = list(i.lower())
  newArr = np.array(newList)
  if newArr[0] == "p":
    print(i + ":", True)
  else:
    print(i + ":", False)




3-1
Sorted List: ['JS' 'PHP' 'Python' 'examples' 'html']
Python Sorted Index: [2]
JS Sorted Index: [0]
examples Sorted Index: [3]
PHP Sorted Index: [1]
html Sorted Index: [4]


3-2
Python: True
JS: False
examples: False
PHP: True
html: False


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

print("4-1")
print(student_id)
print(np.flip(student_id))

print("\n")
print("4-2")
sortedNum = np.sort(student_id)
finalSort = np.flip(sortedNum)
print("The 3 largest values are:", finalSort[0:3])


4-1
[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]


4-2
The 3 largest values are: [6230 5241 5202]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
multiples3 = np.arange(0,100,3)
multiples5 = np.arange(0,100,5)
sum3 = np.sum(multiples3)
sum5 = np.sum(multiples5)

print("The sum is", sum3 + sum5)


The sum is 2633


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print("Original array:")
print(arr)

print("\n")
print("6-1")
arr[:, [1,2]] = arr[:, [2,1]]
print("New array:")
print(arr)

print("\n")
print("6-2")
arr = np.arange(12).reshape(3,4)
arr[[0,1], :] = arr[[1,0],:]
print("New array:")
print(arr)




Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


6-1
New array:
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]


6-2
New array:
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
